node {
  def project = 'huaxin'
  def appName = 'huaxin'
  def feSvcName = "${appName}-frontend"
  def imageTag = "10.10.103.185:5000/changfayu/myapp"
  checkout scm

  stage 'Build image'
  sh("./test.sh")

  stage 'Run mvn tests'
  sh("docker run ${imageTag} mvn clean install")

  stage 'Push image to registry'
  sh("docker push ${imageTag}")

  stage "Deploy Application"
  switch (env.BRANCH_NAME) {
    // Roll out to staging
    case "staging":
        // Change deployed image in staging to the one we just built
        sh("sed -i.bak 's#${imageTag}#' ./k8s/staging/*.yaml")
//        sh("kubectl --namespace=production apply -f k8s/services/")
        sh("kubectl --namespace=production apply -f k8s/staging/")
        sh("echo http://`kubectl --namespace=production get service/${feSvcName} --output=json | jq -r '.status.loadBalancer.ingress[0].ip'` > ${feSvcName}")
        break

    // Roll out to production
    case "master":
        // Change deployed image in staging to the one we just built
        sh("sed -i.bak 's#10.10.103.185:5000/changfayu/myapp#${imageTag}#' ./k8s/production/*.yaml")
//        sh("kubectl --namespace=production apply -f k8s/services/")
        sh("kubectl --namespace=production apply -f k8s/production/")
        sh("echo http://`kubectl --namespace=production get service/${feSvcName} --output=json | jq -r '.status.loadBalancer.ingress[0].ip'` > ${feSvcName}")
        break

    // Roll out a dev environment
    default:
        // Create namespace if it doesn't exist
        sh("kubectl get ns ${env.BRANCH_NAME} || kubectl create ns ${env.BRANCH_NAME}")
        // Don't use public load balancing for development branches
//        sh("sed -i.bak 's#LoadBalancer#ClusterIP#' ./k8s/services/frontend.yaml")
        sh("sed -i.bak 's#10.10.103.185:5000/changfayu/myapp#${imageTag}#' ./k8s/dev/*.yaml")
//        sh("kubectl --namespace=${env.BRANCH_NAME} apply -f k8s/services/")
        sh("kubectl --namespace=${env.BRANCH_NAME} apply -f k8s/dev/")
        echo 'To access your environment run `kubectl proxy`'
//        echo "Then access your service via http://localhost:8001/api/v1/proxy/namespaces/${env.BRANCH_NAME}/services/${feSvcName}:80/"
  }
}

